name: flutter_widget_to_pdf
description: "Convert view into PDF"
version: 0.0.1
homepage: https://github.com/TimothyGCY/flutter_widget_to_pdf.git

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.bleckshiba.flutter_widget_to_pdf
        pluginClass: FlutterWidgetToPdfPlugin
      ios:
        pluginClass: FlutterWidgetToPdfPlugin
